package cn.net.yto.net;

public enum UrlType {
	LOGIN, VERSION_CHECK, LOGOUT, MODIFY_PSW, BASIC_DATA,
	DOWNLOAD_ORDER, MODIFY_ORDER_STATUS, SUBMIT_RECEIVE, UPDATE_RECEIVE,
	SUBMIT_SIGNEDLOG,UPDATE_SIGNEDLOG,CANCEL_RECEIVE,REPLACE_RECEIVE, DELETE_SIGNEDLOG,
	DOWNLOAD_ORDER_CANCEL, UPDATE_ORDER_CANCEL, 
	QUERY_RECEIVE_INFO, QUERY_EXPRESS_TRACE, QUERY_FEE
}
